import { useState, useCallback } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, List } from 'antd';

const data = [
    'Racing car sprays burning fuel into crowd.',
    'Japanese princess to wed commoner.',
    'Australian walks 100km after outback crash.',
    'Man charged over missing wedding girl.',
    'Los Angeles battles huge wildfires.',
  ];
export default function Home() {
    const [ pagination, setPagination ] = useState({ page: 1, total: data.length, limit: 10 });

    const onShowSizeChange = useCallback((current, size) => {
        setPagination({...pagination, page: 1, limit: size})
    }, [ pagination ]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <List
                    bordered
                    dataSource={data}
                    renderItem={item => (
                        <List.Item>
                            {item}
                        </List.Item>
                    )}
                    pagination={{
                        size: 'small',
                        onChange: page => { console.log(page); },
                        current: pagination.page,
                        pageSize: pagination.limit,
                        total: pagination.total,
                        showSizeChanger: true,
                        onShowSizeChange: { onShowSizeChange }
                    }}
                    />
                <Button>click</Button>
            </main>
        </div>
    )
}
